# Generated by Django 3.2.6 on 2021-08-27 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('seen', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[(1, 'Pending'), (2, 'OnGoing'), (3, 'Completed')], default=1, max_length=100)),
                ('priority', models.CharField(choices=[(1, 'High'), (2, 'Moderate'), (3, 'Low')], default=3, max_length=100, null=True)),
                ('image_1', models.ImageField(null=True, upload_to='')),
                ('image_2', models.ImageField(null=True, upload_to='')),
                ('image_3', models.ImageField(null=True, upload_to='')),
                ('image_4', models.ImageField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
