# Generated by Django 3.2.6 on 2021-08-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('1', 'High'), ('2', 'Moderate'), ('3', 'Low')], default='3', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'OnGoing'), ('3', 'Completed')], default='1', max_length=100),
        ),
    ]
