# Generated by Django 3.2.6 on 2021-08-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaints', '0002_auto_20210827_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='image_1',
            field=models.ImageField(null=True, upload_to='image/complaints/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='image_2',
            field=models.ImageField(null=True, upload_to='image/complaints/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='image_3',
            field=models.ImageField(null=True, upload_to='image/complaints/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='image_4',
            field=models.ImageField(null=True, upload_to='image/complaints/'),
        ),
    ]
