# Generated by Django 3.2.6 on 2021-08-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaints', '0003_auto_20210828_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='contact',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='long',
            field=models.FloatField(null=True),
        ),
    ]
