# Generated by Django 3.2.6 on 2021-08-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaints', '0004_auto_20210828_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
