# Generated by Django 3.2.6 on 2021-08-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaints', '0005_complaint_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
