# Generated by Django 3.2.6 on 2021-08-30 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Complaints', '0007_alter_complaint_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='to',
        ),
    ]
