# Generated by Django 3.2.6 on 2021-08-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaints', '0008_remove_complaint_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='image/complaints/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='image/complaints/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='image/complaints/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='image/complaints/'),
        ),
    ]
