# Generated by Django 3.2.6 on 2021-08-31 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Complaints', '0009_auto_20210830_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='image_4',
        ),
    ]
