# Generated by Django 3.2.6 on 2021-08-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaints', '0010_auto_20210831_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='image/complaints/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='image/complaints/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='image/complaints/'),
        ),
    ]
