# Generated by Django 3.2 on 2021-06-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_contactnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='User Description'),
        ),
    ]
